
os: linux
dist: xenial 

sudo: false

language: generic

before_install:
  - gem install bundler -v '< 2'
     
cache:
  # Cache Ruby bundles
  - bundler
  - directories:
    - $TRAVIS_BUILD_DIR/tmp/.htmlproofer #https://github.com/gjtorikian/html-proofer/issues/381
    - /usr/local/lib/python3.3/dist-packages/pip/

# Assume bundler is being used, therefore
# the `install` step will run `bundle install` by default.
# before-install:       "libcurl4-openssl-dev" # https://github.com/gjtorikian/html-proofer/issues/376#issuecomment-332767999

script: 
- "bash -ex .travis-ci.sh"
- bundle install

env:
  global:
  - NOKOGIRI_USE_SYSTEM_LIBRARIES=true # speeds up installation of html-proofer

matrix:
  fast_finish: true
  include:
    - rvm: 2.2.5
      env: TASK='htmlproofer'
    - rvm: 2.2.5
      env: TASK='htmlproofer-external'
    - rvm: 2.2.5
      env: TASK='yip-validator'
    - python: 3.3
      env: TASK='codespell'
      before_script: "sudo pip install urllib3[secure] && sudo pip install codespell"
  allow_failures:
    - rvm: 2.2.5
      env: TASK='htmlproofer-external'

# this is for automating merge's through a GitHub Bot
#notifications:
#  webhooks:
#    urls:
#      - https://bakatsar-1.appspot.com/merge/
#    on_success: always


deploy:
  provider: pages
  local_dir: output
  skip_cleanup: true
  github_token: $GITHUB_TOKEN  # Set in the settings page of your repository, as a secure variable
  keep_history: true
  target_branch: gh-pages
  on:
    branch: master
